### PR TITLE
Added support to Xamarin Studio 6 / MonoDevelop 6

### PR DESCRIPTION
**Pull request by nchicas**

### CODE REVIEW

**Comment by anaselhajjaji** [comment]
Hello @nchicas 

Thank you very much for the pull request.

I'm testing this and am unable to compile the addin in Xamarin Studio 5.10, is it normal? there is no compatibility with previous versions of Xamarin Studio / MonoDevelop ?

**Comment by nchicas** [comment]
Hello Anas,

You can check the original repo from which I forked mine or please check
the previous commit, the latest is compatible with XS6 only.

**Comment by anaselhajjaji** [comment]
Hi

Should I understand that we can't have addin compatible with both XS5 and XS6?

Kind Regards.

**Comment by nchicas** [comment]
Oh wait, you are the owner of the repo I forked hahaha. I only added
support to the latest, since is the most used version.

**Comment by nchicas** [comment]
Anas,

Yes, that's exactly the case!

**Comment by anaselhajjaji** [comment]
Ok perfect. Thank you very much.

**Comment by ascuderibjss** [comment]
Hi @nchicas,
Can you help me to install the plugin on Xamarin 6.1.1?
What I need to do in order to create the add-ins package?

**Comment by nchicas** [comment]
Hi Andrea,

You just need to compile the project and a file will be created (don't
remember the extension), after that in Xamarin just go to plugins, add and
select the generated file.

2016-10-31 12:16 GMT-06:00 Andrea Scuderi notifications@github.com:

**Comment by anaselhajjaji** [comment]
Sorry for the delay, I'm planning to integrate the changes and publish the addin to the gallery.

**Pull request merged**
